blank_issues_enabled: false
contact_links:
  - name: Наш Discord сервер
    url: https://discord.gg/QU6s5xnyRe
    about: Задайте вопрос по разработке или обсудите геймплей здесь (https://discord.gg/QU6s5xnyRe).

  - name: "⚖️ Апелляция банов"
    url: "https://discord.gg/QU6s5xnyRe"
    about: "Если вас забанили в игре, не пишите на GitHub. Используйте эту ссылку."
